import{S as P,i as h,a as k}from"./assets/vendor-CkcXhjHS.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const S=document.querySelector(".app-form"),p=document.querySelector("#galleryList");let E,r=1,l;console.log(`
  Merhaba! 👋
  Kodluyoruz Front-End Eğitimi kapsamında hazırlamış olduğum bu projede
  Axios, IziToast ve SimpleLightbox kütüphanelerini kullanarak bir fotoğraf
  galerisi oluşturmayı hedefledim. Projeyi beğendiyseniz ⭐️'layarak beni
  mutlu edebilirsiniz. Eğer projeyi geliştirmek isterseniz lütfen GitHub
  üzerinden forklayın ve istediğiniz gibi değiştirin. Eğitim sürecinde
  bana destek olan herkese teşekkür ederim. Hadi başlayalım! 🚀


  Search Photos API: https://pixabay.com/api/docs/

  Search Active Page: ${r}
  Search Max Page: ${l}
  `);const b=s=>{const a=document.createElement("li");a.classList.add("gallery-item"),a.dataset.source=s.largeImageURL;const i=document.createElement("a");i.href=s.largeImageURL,i.classList.add("gallery-link"),i.style.color="black";const n=document.createElement("img");n.src=s.webformatURL,n.alt=s.tags,n.width=360,n.height=200;const e=document.createElement("div");e.classList.add("content");const t=document.createElement("div");t.classList.add("info");const o=document.createElement("h5");o.classList.add("key"),o.textContent="Likes",t.appendChild(o);const u=document.createElement("p");u.classList.add("value"),u.textContent=s.likes,t.appendChild(u);const c=document.createElement("div");c.classList.add("info");const g=document.createElement("h5");g.classList.add("key"),g.textContent="Views",c.appendChild(g);const y=document.createElement("p");y.classList.add("value"),y.textContent=s.views,c.appendChild(y);const d=document.createElement("div");d.classList.add("info");const f=document.createElement("h5");f.classList.add("key"),f.textContent="Comments",d.appendChild(f);const L=document.createElement("p");L.classList.add("value"),L.textContent=s.views,d.appendChild(L);const m=document.createElement("div");m.classList.add("info");const C=document.createElement("h5");C.classList.add("key"),C.textContent="Downloads",m.appendChild(C);const v=document.createElement("p");v.classList.add("value"),v.textContent=s.downloads,m.appendChild(v),e.appendChild(t),e.appendChild(c),e.appendChild(d),e.appendChild(m),i.appendChild(n),a.appendChild(e),a.appendChild(i),p.appendChild(a)};let x=new P(".gallery li > a",{captionsData:"alt",captionDelay:350});const w=(s,a)=>new Promise(async(i,n)=>{if(console.log("SearchPhotos() ",s,a),a>l)r=1,a=1;else{const e=await k.get("https://pixabay.com/api/",{params:{key:"21250106-0015933422f1e636de5f184b8",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:40}});l=parseFloat(e.data.totalHits/e.data.hits.length).toFixed(0),console.log(`
        Search Active Text: ${E}
        Search Active Page: ${r}
        Search Max Page: ${l}
      `),e.data.hits.length===0&&h.error({position:"topRight",color:"red",message:"Sorry, there are no images matching your search query. Please try again!"}),r<l&&(document.querySelector("#nextPage").style.display="block"),i(e)}});S.addEventListener("submit",async s=>{s.preventDefault(),p.innerHTML="";const a=s.target.elements.search.value;if(E=a,r=1,l=void 0,a==="")return h.warning({position:"topRight",message:"Please enter a valid search query!"}),!1;{const i=document.createElement("li");i.classList.add("gallery-item");const n=document.createElement("span");n.classList.add("loader"),i.appendChild(n),i.style.textAlign="center",i.style.border="none",p.appendChild(i);const t=(await w(a,r)).data.hits;p.innerHTML="",t.length===0?h.error({position:"topRight",color:"red",message:"Sorry, there are no images matching your search query. Please try again!"}):(t.forEach(o=>{b(o)}),x.refresh()),s.target.reset()}});document.querySelector("#nextPage").addEventListener("click",async s=>{r++;const n=(await w(E,r)).data.hits;if(n.length===0)h.error({position:"topRight",color:"red",message:"Sorry, there are no images matching your search query. Please try again!"});else{n.forEach(t=>{b(t)});const e=document.querySelector(".gallery img");if(e){const t=e.getBoundingClientRect().height;window.scrollBy({top:t*2.75,behavior:"smooth"})}x.refresh()}});
//# sourceMappingURL=index.js.map
